### ISSUE TITLE
Error: invalid Module.php file

### ISSUE THREAD

**Issue by jmcgranahan** [Daniel-KM/Omeka-S-module-Lockout#1]
I downloaded and loaded this module into our instance of Omeka-S, running 1.4, but get the error above - "Error: invalid Module.php file". Is this module not compatible with 1.4? I know 2.0.2 is available, but it is going to require a PHP upgrade on our server (5 to 7). Please advise. Thank you.

**Comment by Daniel-KM** [comment]
You have to rename the folder to Lockout.

**Comment by jmcgranahan** [comment]
It would appear this is not compatible with Omeka-S 2.0.2

**Comment by Daniel-KM** [comment]
Try to change the version constraint in `config/module.ini`: 
omeka_version_constraint = "^1.0.0 || ^2.0.0"

**Comment by jmcgranahan** [comment]
that did it - thanks!
