### ISSUE TITLE
Module not registered

### ISSUE THREAD

**Issue by symac** [Daniel-KM/Omeka-S-module-Lockout#2]
It seems the module is not registered on [the official module page](https://omeka.org/s/modules/). If it's on purpose that's fine, otherwise it would be great to add it.

**Comment by Daniel-KM** [comment]
En fait, mes modules sont libres et n'importe qui peut les mettre sur le site officiel (en donnant bien sûr toutes ses infos à Google, qui gère le formulaire pour des raisons inconnues).

**Comment by symac** [comment]
Merci @Daniel-KM pour cette précision, voyant de nombreux autres de vos modules sur cette liste je pensais que c'était un oubli de ne pas avoir signalé ce lockout, je m'occuperai donc de le signaler. Merci pour la réponse.
